spring.datasource.url=jdbc:postgresql://gondola.proxy.rlwy.net:22584/railway
spring.datasource.username=postgres
spring.datasource.password=QZJHOvEWneacLJoFeroXHWLhvWXYlbZv

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true